"""add gov_jobs table

Revision ID: 07624fb82111
Revises: 17b109925252
Create Date: 2026-04-24 11:12:32.082913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07624fb82111'
down_revision: Union[str, Sequence[str], None] = '17b109925252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gov_jobs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('gov_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gov_jobs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_job_id'), table_name='gov_jobs')
    op.drop_index(op.f('idx_profile_task'), table_name='gov_jobs')
    op.drop_index(op.f('job_id'), table_name='gov_jobs')
    op.create_index(op.f('ix_gov_jobs_id'), 'gov_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_gov_jobs_job_id'), 'gov_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_gov_jobs_profile_id'), 'gov_jobs', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gov_jobs_profile_id'), table_name='gov_jobs')
    op.drop_index(op.f('ix_gov_jobs_job_id'), table_name='gov_jobs')
    op.drop_index(op.f('ix_gov_jobs_id'), table_name='gov_jobs')
    op.create_index(op.f('job_id'), 'gov_jobs', ['job_id'], unique=True)
    op.create_index(op.f('idx_profile_task'), 'gov_jobs', ['profile_id', 'task_name'], unique=False)
    op.create_index(op.f('idx_job_id'), 'gov_jobs', ['job_id'], unique=False)
    op.alter_column('gov_jobs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('gov_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('gov_jobs', 'deleted_at')
    # ### end Alembic commands ###
