"""add_accounting_extra_fields

Revision ID: 17b109925252
Revises: dd0d703e40f0
Create Date: 2026-04-23 12:02:38.765250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b109925252'
down_revision: Union[str, Sequence[str], None] = 'dd0d703e40f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('accounting_gender', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('accounting_birth_date', sa.Date(), nullable=True))
    op.add_column('companies', sa.Column('accounting_id_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'accounting_id_number')
    op.drop_column('companies', 'accounting_birth_date')
    op.drop_column('companies', 'accounting_gender')
    # ### end Alembic commands ###
