"""add_ocr_logs

Revision ID: 2b72ea5757d0
Revises: c1a2b3d4e5f6
Create Date: 2026-04-21 10:41:44.425086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b72ea5757d0'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('drive_link', sa.String(length=500), nullable=True),
    sa.Column('raw_result', sa.JSON(), nullable=True),
    sa.Column('fields_result', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_logs_id'), 'ocr_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ocr_logs_user_id'), 'ocr_logs', ['user_id'], unique=False)
    op.drop_index('code', table_name='companies')
    op.create_index(op.f('ix_companies_code'), 'companies', ['code'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_company_persons_id'), 'company_persons', ['id'], unique=False)
    op.alter_column('company_positions', 'is_llc1',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('company_positions', 'is_llc2',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('company_positions', 'is_jsc',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_company_positions_id'), 'company_positions', ['id'], unique=False)
    op.drop_index('household_id', table_name='profile_industries')
    op.drop_index('ix_household_industries_id', table_name='profile_industries')
    op.create_index(op.f('ix_profile_industries_id'), 'profile_industries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_industries_id'), table_name='profile_industries')
    op.create_index('ix_household_industries_id', 'profile_industries', ['id'], unique=False)
    op.create_index('household_id', 'profile_industries', ['profile_id'], unique=False)
    op.drop_index(op.f('ix_company_positions_id'), table_name='company_positions')
    op.alter_column('company_positions', 'is_jsc',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('company_positions', 'is_llc2',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('company_positions', 'is_llc1',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_company_persons_id'), table_name='company_persons')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_code'), table_name='companies')
    op.create_index('code', 'companies', ['code'], unique=True)
    op.drop_index(op.f('ix_ocr_logs_user_id'), table_name='ocr_logs')
    op.drop_index(op.f('ix_ocr_logs_id'), table_name='ocr_logs')
    op.drop_table('ocr_logs')
    # ### end Alembic commands ###
