"""add_user_fields_manager

Revision ID: dd0d703e40f0
Revises: 2b72ea5757d0
Create Date: 2026-04-22 11:17:33.517565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dd0d703e40f0'
down_revision: Union[str, Sequence[str], None] = '2b72ea5757d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('personal_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('gender', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('id_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'manager_id')
    op.drop_column('users', 'address')
    op.drop_column('users', 'id_number')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'personal_email')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
