"""Add customer and config tables

Revision ID: f9a0d68e2dc8
Revises: aa1dc6226621
Create Date: 2026-04-11 15:42:12.068280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a0d68e2dc8'
down_revision: Union[str, Sequence[str], None] = 'aa1dc6226621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_configs',
    sa.Column('crm_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_configs_crm_id'), 'source_configs', ['crm_id'], unique=True)
    op.create_index(op.f('ix_source_configs_id'), 'source_configs', ['id'], unique=False)
    op.create_table('staff_configs',
    sa.Column('crm_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_configs_crm_id'), 'staff_configs', ['crm_id'], unique=True)
    op.create_index(op.f('ix_staff_configs_id'), 'staff_configs', ['id'], unique=False)
    op.create_table('status_configs',
    sa.Column('crm_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_configs_crm_id'), 'status_configs', ['crm_id'], unique=True)
    op.create_index(op.f('ix_status_configs_id'), 'status_configs', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source_configs.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_configs.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.add_column('business_households', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'business_households', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_households', type_='foreignkey')
    op.drop_column('business_households', 'customer_id')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_status_configs_id'), table_name='status_configs')
    op.drop_index(op.f('ix_status_configs_crm_id'), table_name='status_configs')
    op.drop_table('status_configs')
    op.drop_index(op.f('ix_staff_configs_id'), table_name='staff_configs')
    op.drop_index(op.f('ix_staff_configs_crm_id'), table_name='staff_configs')
    op.drop_table('staff_configs')
    op.drop_index(op.f('ix_source_configs_id'), table_name='source_configs')
    op.drop_index(op.f('ix_source_configs_crm_id'), table_name='source_configs')
    op.drop_table('source_configs')
    # ### end Alembic commands ###
