"""Add crm_link column to Customer and HKD

Revision ID: 3986bab786d4
Revises: 3e3f299d0a2c
Create Date: 2026-04-11 18:47:24.997699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3986bab786d4'
down_revision: Union[str, Sequence[str], None] = '3e3f299d0a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_households', sa.Column('crm_link', sa.String(length=500), nullable=True))
    op.add_column('customers', sa.Column('crm_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'crm_link')
    op.drop_column('business_households', 'crm_link')
    # ### end Alembic commands ###
