"""Add tracking fields and notes to HKD

Revision ID: 3e3f299d0a2c
Revises: f9a0d68e2dc8
Create Date: 2026-04-11 18:01:29.061741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3f299d0a2c'
down_revision: Union[str, Sequence[str], None] = 'f9a0d68e2dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_households', sa.Column('handling_staff_id', sa.Integer(), nullable=True))
    op.add_column('business_households', sa.Column('supporting_staff_id', sa.Integer(), nullable=True))
    op.add_column('business_households', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('business_households', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('business_households', sa.Column('note', sa.String(length=2000), nullable=True))
    op.create_foreign_key(None, 'business_households', 'source_configs', ['source_id'], ['id'])
    op.create_foreign_key(None, 'business_households', 'staff_configs', ['supporting_staff_id'], ['id'])
    op.create_foreign_key(None, 'business_households', 'status_configs', ['status_id'], ['id'])
    op.create_foreign_key(None, 'business_households', 'staff_configs', ['handling_staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_households', type_='foreignkey')
    op.drop_constraint(None, 'business_households', type_='foreignkey')
    op.drop_constraint(None, 'business_households', type_='foreignkey')
    op.drop_constraint(None, 'business_households', type_='foreignkey')
    op.drop_column('business_households', 'note')
    op.drop_column('business_households', 'source_id')
    op.drop_column('business_households', 'status_id')
    op.drop_column('business_households', 'supporting_staff_id')
    op.drop_column('business_households', 'handling_staff_id')
    # ### end Alembic commands ###
