"""add documents table, folder_id hkd, id_crm customer

Revision ID: 7d38b1210b52
Revises: 970f7c3ecadb
Create Date: 2026-04-12 18:36:07.334627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d38b1210b52'
down_revision: Union[str, Sequence[str], None] = '970f7c3ecadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
