"""add documents table, folder_id hkd, id_crm customer

Revision ID: 970f7c3ecadb
Revises: dba550615793
Create Date: 2026-04-12 18:32:13.739196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970f7c3ecadb'
down_revision: Union[str, Sequence[str], None] = 'dba550615793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_households', sa.Column('folder_id', sa.String(length=200), nullable=True))
    op.add_column('customers', sa.Column('id_crm', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'id_crm')
    op.drop_column('business_households', 'folder_id')
    # ### end Alembic commands ###
