"""add id_crm to business_households

Revision ID: aa5e2268336a
Revises: ebbac34f658f
Create Date: 2026-04-13 08:24:53.920630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5e2268336a'
down_revision: Union[str, Sequence[str], None] = 'ebbac34f658f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_households', sa.Column('id_crm', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_households', 'id_crm')
    # ### end Alembic commands ###
