"""add_customer_personal_info_and_hkd_paid_amount

Revision ID: dba550615793
Revises: 9ddfbd48f76a
Create Date: 2026-04-11 23:24:41.835262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba550615793'
down_revision: Union[str, Sequence[str], None] = '9ddfbd48f76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_households', sa.Column('paid_amount', sa.BigInteger(), nullable=True))
    op.add_column('customers', sa.Column('id_card', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('gender', sa.SmallInteger(), nullable=True))
    op.add_column('customers', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('province_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('ward_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('street', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'customers', 'administrative_units', ['district_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'administrative_units', ['ward_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'administrative_units', ['province_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'street')
    op.drop_column('customers', 'ward_id')
    op.drop_column('customers', 'district_id')
    op.drop_column('customers', 'province_id')
    op.drop_column('customers', 'birth_date')
    op.drop_column('customers', 'gender')
    op.drop_column('customers', 'id_card')
    op.drop_column('business_households', 'paid_amount')
    # ### end Alembic commands ###
